# Generated by Django 5.1.4 on 2025-02-13 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0002_category_image_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
