# Generated by Django 5.1.4 on 2025-02-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0005_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
