# Generated by Django 5.1.4 on 2025-02-26 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0006_meal_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'verbose_name': 'Taom', 'verbose_name_plural': 'Taomlar'},
        ),
    ]
