# Generated by Django 5.1.4 on 2025-02-26 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0007_alter_meal_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
    ]
