# Generated by Django 5.1.4 on 2025-02-26 12:51

import shortuuidfield.fields
from django.db import migrations


from django.db import migrations
import shortuuid

def populate_slug(apps, schema_editor):
    Meal = apps.get_model('meal', 'Meal')
    for meal in Meal.objects.filter(slug__isnull=True):
        meal.slug = shortuuid.ShortUUIDField().generate()  # You can use any logic to generate slugs
        meal.save()

class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0008_alter_category_options'),  # Replace with the actual last migration file name
    ]

    operations = [
        migrations.RunPython(populate_slug),
    ]
