# Generated by Django 5.1.4 on 2025-02-26 12:56

import shortuuidfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0009_alter_meal_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='slug',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, db_index=True, default='ddd', editable=False, max_length=22, unique=True),
            preserve_default=False,
        ),
    ]
