# Generated by Django 5.1.4 on 2025-03-01 08:25

import shortuuid.main
import shortuuidfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0013_alter_meal_image_alter_meal_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='price',
            field=models.CharField(default='1', max_length=32),
        ),
        migrations.AlterField(
            model_name='meal',
            name='slug',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, db_index=True, default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
    ]
