# Generated by Django 5.1.4 on 2025-03-02 11:14

import django.db.models.deletion
import shortuuid.main
import shortuuidfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0015_alter_meal_price_alter_meal_slug'),
        ('restaurant', '0008_alter_restaurant_payment_period_alter_restaurant_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='restaurant.restaurant'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='slug',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, db_index=True, default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
    ]
