# Generated by Django 5.1.4 on 2025-03-02 06:49

import shortuuid.main
import shortuuidfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0017_alter_meal_category_alter_meal_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='slug',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, db_index=True, default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
    ]
