# Generated by Django 5.1.4 on 2025-02-02 14:56

import restaurant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('uid', models.CharField(default=restaurant.models.generate_uid, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField(blank=True)),
                ('brand_logo', models.ImageField(blank=True, default='restaurants/default.jpg', upload_to='restaurants')),
                ('background_image', models.ImageField(blank=True, default='restaurants/default.jpg', upload_to='restaurants')),
                ('insta_link', models.CharField(blank=True, max_length=48, null=True)),
                ('short_video', models.CharField(blank=True, max_length=48, null=True)),
            ],
        ),
    ]
