# Generated by Django 5.1.4 on 2025-02-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_restaurant_background_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='background_image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='restaurants'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='brand_logo',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='restaurants'),
        ),
    ]
