# Generated by Django 5.1.4 on 2025-02-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_restaurant_insta_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='menu_design',
            field=models.IntegerField(default=2),
        ),
    ]
