# Generated by Django 5.1.4 on 2025-02-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_restaurant_menu_design'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='menu_design',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
