# Generated by Django 5.1.4 on 2025-02-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_restaurant_menu_design'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='payment_period',
            field=models.IntegerField(default=1, help_text='Subscription duration in months'),
        ),
    ]
