# Generated by Django 5.1.4 on 2025-02-14 07:52

import restaurant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_restaurant_expiration_date_restaurant_payment_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='payment_period',
            field=models.IntegerField(default=3, help_text='Subscription duration in months'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='uid',
            field=models.CharField(db_index=True, default=restaurant.models.generate_uid, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
