# Generated by Django 5.1.4 on 2025-03-02 06:52

import shortuuid.main
import shortuuidfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_alter_restaurant_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='uid',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, db_index=True, default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False, unique=True),
        ),
    ]
