# Generated by Django 5.1.4 on 2025-03-09 06:36

import restaurant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_alter_restaurant_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='meal_limit',
            field=models.IntegerField(blank=True, default=200, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='uid',
            field=models.CharField(db_index=True, default=restaurant.models.generate_uid, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
