# Generated by Django 5.1.4 on 2025-02-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_owner',
            field=models.BooleanField(blank=True, default=False, editable=False, null=True),
        ),
    ]
