# Generated by Django 5.1.4 on 2025-02-15 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_is_owner_user_is_dev'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_dev',
            new_name='is_developer',
        ),
    ]
